version: '3'
services:
  chips:
    build: .
    command: npm run start-dev
    restart: always
    environment:
      - TEMPLATING_ENGINE
    volumes:
      - .:/usr/src/app
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "80:3000"
      - "9229:9229"
      - "9228:9228"
  guacd:
    restart: always
    image: linuxserver/guacd
    container_name: guacd

  rdesktop:
    restart: always
    image: linuxserver/rdesktop
    container_name: rdesktop
    volumes:
      - ./shared:/shared
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London