# Generated by Django 2.2.12 on 2020-04-24 13:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('userid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('firstname', models.CharField(max_length=64)),
                ('lastname', models.CharField(max_length=64)),
                ('bio', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=64)),
                ('location', models.CharField(max_length=64)),
                ('avatar', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Sqeak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sqeak_text', models.CharField(max_length=256)),
                ('created_date', models.DateTimeField()),
                ('likes', models.ManyToManyField(blank=True, related_name='owner', through='api.Like', to='api.UserProfile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='like',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.UserProfile'),
        ),
        migrations.AddField(
            model_name='like',
            name='sqeak',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Sqeak'),
        ),
    ]
